#!/usr/bin/env node
// Generates data/codes.ts: the Code 128 bars of the handle and the QR of the
// résumé, from two trusted tools (zint and qrencode) so the site carries no
// barcode library and no hand-typed pattern table. Run again after changing
// the handle in data/portfolio.ts or the site url in lib/site.ts:
//
//   node scripts/codes.mjs
//
import { execFileSync } from 'node:child_process'
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

const root = join(import.meta.dirname, '..')
const handle = /handle:\s*'([^']+)'/.exec(readFileSync(join(root, 'data/portfolio.ts'), 'utf8'))?.[1]
const site = /SITE = '([^']+)'/.exec(readFileSync(join(root, 'lib/site.ts'), 'utf8'))?.[1]
if (!handle || !site) throw new Error('could not read the handle or the site url')
const url = `${site}/resume.pdf`

// Code 128 (zint symbology 20), one module per unit: the bars are one path
// of "M{x} 0h{w}v{h}h-{w}Z" runs
const tmp = mkdtempSync(join(tmpdir(), 'codes-'))
execFileSync('zint', ['-b', '20', '--scale', '1', '--notext', '--data', handle, '-o', join(tmp, 'code128.svg')])
const svg = readFileSync(join(tmp, 'code128.svg'), 'utf8')
const raw = [...svg.matchAll(/M([\d.]+) 0h([\d.]+)/g)].map((m) => [Number(m[1]), Number(m[2])])
const width = Number(/width="([\d.]+)"/.exec(svg)?.[1])
if (!raw.length || !width) throw new Error('could not parse the zint svg')
// zint's svg units are half modules; the narrowest bar is one module
const unit = Math.min(...raw.map(([, w]) => w))
const bars = raw.map(([x, w]) => [x / unit, w / unit])
const modules = width / unit

// QR, error level M, no margin: qrencode prints two characters per module (ASCII, not ASCIIi: that one is the negative)
const ascii = execFileSync('qrencode', ['-l', 'M', '-m', '0', '-t', 'ASCII', '-o', '-', url]).toString()
const qr = ascii
  .split('\n')
  .filter((l) => l.length)
  .map((l) => l.match(/.{2}/g).map((c) => (c === '##' ? '#' : '.')).join(''))
if (qr.some((r) => r.length !== qr.length)) throw new Error('the qr is not square')

const out = `// generated by scripts/codes.mjs - do not edit by hand
// (run it again after changing the handle or the site url)

/** the label's two codes, as zint and qrencode drew them */
export const codes = {
  handle: '${handle}',
  /** Code 128: the symbol is \`modules\` wide, each bar is [x, width] in modules */
  barcode: {
    modules: ${modules},
    bars: ${JSON.stringify(bars)} as [number, number][],
  },
  url: '${url}',
  /** QR (level M), one row per string, '#' is a dark module */
  qr: [
${qr.map((r) => `    '${r}',`).join('\n')}
  ],
}
`
writeFileSync(join(root, 'data/codes.ts'), out)
console.log(`data/codes.ts: barcode ${bars.length} bars / ${modules} modules, qr ${qr.length}x${qr.length}, ${url}`)
